version: '3.7'

services:

  web:
    image: mycargus/hello_docker_world:latest
    environment:
      VIRTUAL_HOST: hello.docker
    networks:
      - watir-docker-grid-network

  testrunner:
    build:
      context: .
    environment:
      APP_HOST: web:80
      HUB_HOST: hub:4444
    volumes:
      - .:/usr/src/app
    networks:
      - watir-docker-grid-network

  hub:
    image: selenium/hub:3.141.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      GRID_BROWSER_TIMEOUT: 10000 # 10 seconds
      GRID_NEW_SESSION_WAIT_TIMEOUT: 20000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 10000
      VIRTUAL_HOST: selenium.hub.docker
    ports:
      - "4444:4444"
    networks:
      - watir-docker-grid-network

  node-firefox:
    image: selenium/node-firefox:3.141.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment: &SELENIUM_NODE_ENV
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - "5901:5900"
    networks:
      - watir-docker-grid-network

  node-chrome:
    image: selenium/node-chrome:3.141.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5900:5900"
    networks:
      - watir-docker-grid-network

  node-chrome-debug:
    image: selenium/node-chrome-debug:3.141.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5900:5900"
    networks:
      - watir-docker-grid-network

  node-firefox-debug:
    image: selenium/node-firefox-debug:3.141.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5901:5900"
    networks:
      - watir-docker-grid-network

networks:
  watir-docker-grid-network:
    driver: bridge
    name: watir-docker-grid-network
